#! /bin/bash
NAME=${1:-postgres}
CONTAINER=$(docker ps --format "{{.Names}}" | grep "$NAME")
if [ -z "$CONTAINER" ]
	then
		echo "Container not found"
		exit 1
fi
FILE="wubloader-$(date +%Y-%m-%dT%H:%M:%S).sql"
echo "Dumping $CONTAINER to $FILE"
docker exec $CONTAINER pg_dump wubloader -U postgres > $FILE
aws s3 cp $FILE s3://wubloader-test
rm $FILE
